added movies search
ElenaLadutska/React-tasks pull request #1
Opened 2023-01-19 17:00 UTC by ElenaLadutska

2023-01-22 07:26 UTC, kathrynowy requested changes

2023-01-22 07:26 UTC, kathrynowy commented on my-app/src/App.js
> +    </>
do you need a fragment here?

2023-01-22 07:26 UTC, kathrynowy commented on my-app/src/GetMovies.jsx
> +  const [value, setValue] = useState('');
```suggestion
  const [movies, setMovies] = useState([]);
  
  const [value, setValue] = useState('');
```

2023-01-22 07:26 UTC, kathrynowy commented on my-app/src/GetMovies.jsx
> +    .then(data => setMovies(data))
try/catch

2023-01-22 07:26 UTC, kathrynowy commented on my-app/src/GetMovies.jsx
> +  }, [value]);
? if you don't use value - you don't need to pass variable into the dependencies array

2023-01-22 07:26 UTC, kathrynowy commented on my-app/src/GetMovies.jsx
> +  })
1 use callback и прочитать зачем он нам нужен
2 убрать ретурн

2023-01-22 07:26 UTC, kathrynowy commented on my-app/src/GetMovies.jsx
> +    </>
.

2023-01-23 13:01 UTC, ElenaLadutska commented on my-app/src/App.js
> +    </>
no, removed

2023-01-23 13:01 UTC, ElenaLadutska commented on my-app/src/GetMovies.jsx
> +  const [value, setValue] = useState('');
fixed

2023-01-23 13:02 UTC, ElenaLadutska commented on my-app/src/GetMovies.jsx
> +  }, [value]);
okay, thanks, I removed value from the dependencies array

2023-01-23 13:03 UTC, ElenaLadutska commented on my-app/src/GetMovies.jsx
> +    </>
fixed

2023-01-24 16:11 UTC, ElenaLadutska commented on my-app/src/GetMovies.jsx
> +  })
fixed

2023-02-20 08:52 UTC, kathrynowy requested changes

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/App.js
> +import NotFound from './components/NotFound';
import orders

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/App.js
> +        <Route path='*' element={<NotFound />}/>
map

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/App.js
> +  const [city, setCity] = useState("1");
why do you need it?

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +  let [isLoading, setLoading] = useState(true);
why let??

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +  let [isLoading, setLoading] = useState(true);
why isLoading true ?

isLoading only when you start requesting data

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +      setLoading(isLoading = false);
(((( 
read docs about usestate pls

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +      setLoading(isLoading = false);
for every single useState you have written, it's all wrong

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +    getMovies();
getMovies should be in the dependency array

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +  const [filteredMovies, setFilteredMovies] = useState([]);
at first all useStates
than functionss / useCallbacks

than useEffects

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +      setFilteredMovies(movies.filter(movie => movie.name.toLowerCase().includes(value.toLowerCase())))
too long line

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +      setFilteredMovies(movies.filter(movie => movie.name.toLowerCase().includes(value.toLowerCase())))
you can destructure a few fields here

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +    filterMovies()
use useMemo for filtering movies pls

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +    isLoading ? <Loader /> : (
move above to if statement pls
it looks very bad, unreadable

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +            !!movies.length || (
if we have movies we render we don't have them?

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +        }
what is ''???

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +            filteredMovies.map((movie, index) => (
destructuring

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +          ))
one movie is a component

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/Movies.jsx
> +              <Link to={`/movie-description/${movie.eventId}`}>
i've told this while meeting
we use handler function with router push
not Link

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/components/Button/index.jsx
> +      {props.title}
1. arrow functions
2. destructuring
3 why do you need id here for the btn?

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/components/Cinemas/index.jsx
> +  return (
.
services 
+ remove unnecessary variable

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/components/Cinemas/index.jsx
> +        ? Object.entries(name.film.showList).map(([date, value], index) => (
в беседе

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/components/Cinemas/index.jsx
> +            className="showDate"
naming

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/components/Cinemas/index.jsx
> +          </div>
chat tg

2023-02-20 08:52 UTC, kathrynowy commented on my-app/src/styles/index.css
> +
move all styles to appropriate filders

2023-08-26 20:44 UTC, merged